<?php

namespace App\Services\Status;

/**
 * Class UserStatusService store all user statuses
 * @package App\Services
 */
class UserStatusService {

    const NEW = 'NEW';
    const DONE = 'DONE';
    const SET_START_LANGUAGE = 'SET_START_LANGUAGE';
    const SET_LANGUAGE = 'SET_LANGUAGE';
    const SETTINGS = 'SETTINGS';
    const LOCATION_TYPE_SELECT = 'LOCATION_TYPE_SELECT';
    const SETTINGS_LOCATION_TYPE_SELECT = 'SETTINGS_LOCATION_TYPE_SELECT';
    const SETTINGS_DISTRICT_SELECT = 'SETTINGS_DISTRICT_SELECT';
    const CITY_NAME = 'CITY_NAME';
    const LOCATION_WAITING = 'LOCATION_WAITING';
    const LOCATION_SELECTING = 'LOCATION_SELECTING';
    const SETTINGS_LOCATION_WAITING = 'SETTINGS_LOCATION_WAITING';
    const SETTINGS_LOCATION_SELECTING = 'SETTINGS_LOCATION_SELECTING';
    const SETTINGS_CITY_NAME = 'SETTINGS_CITY_NAME';
    const DISTRICT_SELECT = 'DISTRICT_SELECT';
    const FEEDBACK = 'FEEDBACK';
    const USER_CITY_LIST = 'USER_CITY_LIST';
    const FORECAST_CITY_SELECT = 'FORECAST_CITY_SELECT';
    const CURRENT_CITY_SELECT = 'CURRENT_CITY_SELECT';
    const CITY_MENU = 'CITY_MENU';

}